### PR TITLE
Add viptela to folder based tests

### PR DESCRIPTION
**Pull request by itdependsnetworks**
## Description

Add viptela to folder based tests

## Motivation and Context

A single testing strategy

## Impact (If any)

N/A

## Screenshots:

N/A

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

### CODE REVIEW

**Review by tahigash — CHANGES_REQUESTED** [review]
thanks for contributing this UT change. expected/parsed output files look good.
just update below line to add `viptela`.
https://github.com/CiscoTestAutomation/genieparser/blob/master/tests/ci_folder_parsing.py#L55

**Review by ThomasJRyan — APPROVED** [review]

**Review by jeaubin — APPROVED** [review]
Can you confirm that all testcases has been migrated?

**Comment by itdependsnetworks** [comment]
Yes

**Review by tahigash — APPROVED** [review]
thank you for your contribution. and I took care of conflict and previous my comment.

**Pull request merged**
