### PR TITLE
Fix parser show_device_tracking

### PR DESCRIPTION
**Pull request by alsyz**
## Description
Modified the parser show_device_tracking. updated the regex to match lines that has a time left value.

## Motivation and Context
In the original parser, all lines with a time left value would be ignored thus missing some of the hosts' data in the output.  With the modified code, it is able to convert match those lines with a time left value .

## Impact (If any)
no

## Screenshots:
screenshot

## Checklist:

- [x] I have updated the changelog.
- [not applicable] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

### CODE REVIEW

**Comment by lsheikal** [comment]
Hi @domachad ,
This branch have conflicts kindly resolve it, apart from that its good.

**Comment by lsheikal** [comment]
Hi @alsyz ,
Kindly resolve the branch conflicts, apart from that its good.

**Review by GerriorL — APPROVED** [review]
Might want to make this a folder test instead of a unittest.

**Comment by alsyz** [comment]
committed the new sdk_generator/outputs/github_parser.json  to resolve branch conflicts

**Comment by GerriorL** [comment]
I brought your fork up to date with the current master, and I moved your unittest over to the folder based system as an update.

**Review by lsheikal — APPROVED** [review]

**Pull request merged**
