### PR TITLE
Fix ShowIsisDatabaseDetail

### PR DESCRIPTION
**Pull request by jmdilly**
## Description
Allow multiple adjacencies between nodes

## Motivation and Context
With the current parser, when two nodes have multiple adjacencies, only one of them is saved by the parser. This PR fixes that.

## Impact (If any)
For backward compatibility, the first key is still the neighbor ID of the adjacent node. Additionnal adjacencies have the following key have the following format '<Neighbor_ID>_#' with # >= 1.

## Screenshots:
Changes in the dict:
image

Tests :
image

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [ ] All new code passed compilation.

### CODE REVIEW

**Comment by domachad** [comment]
@jmdilly you didn't have to close the pull request. In fact, it is best if you make the changes in your branch and push them to the same PR. That way, we can keep track of the progress and help you in case something is not working properly.

**Comment by jmdilly** [comment]
> 
> 
> @jmdilly Have you addressed my previous comments? I don't see any changes in your code since my last review

Hello @domachad , yes, I did in these two commits 7101882e8bdb6278023dd0194a9a34b68264f687 &
 053f6335edb73af1c2ac37a779335b1feda2d640 which fix the loop by incrementing correctly variable i and add a smaller and better test illustrating the need of the loop. I also changed the screenshot in the feature description.

Thank you!

**Comment by jmdilly** [comment]
> Make sure if you are using the right branch. If are in the right branch and you can see the files in your local repo, you can try to push them to the remote repo again. There seems to be a conflict with github_parser.json as well. Running `make json` should fix it.

I solved the conflict and pushed the commit.

Respectfully, I do see the previous commits in the history even when I check this PR from an unauthenticated GitHub session. Could you check again in the commits tab (commits of October 14th) ? Or would you like me to close this PR and reopen the new one ?

Thank you!

**Comment by jmdilly** [comment]
Reopened in #586

**Pull request closed without merging**
