### PR TITLE
add GitHub Workflow

### PR DESCRIPTION
**Pull request by k01ek**

### CODE REVIEW

**Comment by KamyarZiabari** [comment]
Merged 112.

**Comment by KamyarZiabari** [comment]
Merged 112!. Thanks again for the contribution

**Comment by KamyarZiabari** [comment]
PR #112 was merged that contains the same content

**Comment by k01ek** [comment]
@KamyarZiabari , Hi! You don't like GitHub workflow for autotests at pull request?? Or there is another reason?

**Comment by KamyarZiabari** [comment]
> @KamyarZiabari , Hi! You don't like GitHub workflow for autotests at pull request?? Or there is another reason?
I did test them in my local environment. But generally, workflow is something that I have not used before, did not want to use it even small on a working situation. I preferred to work with it on my own and  in the future use it for similiar purposes. Thanks for suggesting it.

**Comment by k01ek** [comment]
@KamyarZiabari Ok, I got it! Thank for answer.

**Pull request closed without merging**
