### PR TITLE
Fix for #532

### PR DESCRIPTION
**Pull request by aroravansh**
## Description
Modified the regex in line 99 of show_spanning_tree.py

## Motivation and Context
Enables Network administrators to utilize in multi VLAN deployment

## Impact (If any)
None expected

Support note:
Was created as an issue originally.
image
Closed issue as a fix has been provided by issue creator

### CODE REVIEW

**Review by lsheikal — CHANGES_REQUESTED** [review]
The code seems good. But we need a unit test to cover your changes. You can find examples here. Let me know if you have any other issue.
https://github.com/CiscoTestAutomation/genieparser/tree/master/src/genie/libs/parser/nxos/tests/ShowInterface/cli/equal

**Comment by aroravansh** [comment]
I found another issue with the Parser not working for Physical Interfaces, non-VPC Port Channel, and multiple MST instances. Should I add the other fix to this same PR and update the test case output or create another PR for it?

**Comment by ThomasJRyan** [comment]
> 
> 
> I found another issue with the Parser not working for Physical Interfaces, non-VPC Port Channel, and multiple MST instances. Should I add the other fix to this same PR and update the test case output or create another PR for it?

You can update this PR with it. Still need the unittests though

**Comment by aroravansh** [comment]
Recently in [merge](https://github.com/CiscoTestAutomation/genieparser/commit/2fa1ccd126719164c32c6bd4ea9e0a8308aa07ae), The test files have been deleted. Is there a new way of unittesting and is there any documentation available for it?

**Review by lsheikal — CHANGES_REQUESTED** [review]
Why 3964 files have been changed? i think you made a mistake in merging. Kindly fix it

**Comment by aroravansh** [comment]
Hi @lsheikal 
It appears like the extra files were added after the force push by Daniel, I updated my Pull Request to reflect changes I made.
Thank You 
Vansh Arora

**Review by lsheikal — APPROVED** [review]

**Comment by aroravansh** [comment]
Hi @ThomasJRyan 
 Can you please review and merge when you get a chance
 Thanks 
 Vansh Arora

**Comment by aroravansh** [comment]
Hi @lsheikal 
Is there anything else needed on my part?
Thanks 
Vansh

**Review by lsheikal — CHANGES_REQUESTED** [review]
Is the change backward compatible?

**Comment by aroravansh** [comment]
Yes @lsheikal

**Pull request merged**
