### PR TITLE
Parser created for show wireless profile policy detailed

### PR DESCRIPTION
**Pull request by qduk**
## Description
Parser created for show wireless profile policy detailed

## Screenshots:
Capture

## Checklist:
- [x] I have updated the changelog.
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

### CODE REVIEW

**Review by tahigash — APPROVED** [review]
thanks for contribution! schema is confirmed. My teammate will review code.

**Comment by choudnik** [comment]
@qduk, Can you please work on the review comments and resolve the conflicts? Thanks.

**Comment by qduk** [comment]
@choudnik conflicts have been resolved. Please let me know if anything else is needed. Thanks!

**Comment by choudnik** [comment]
Thanks @qduk. Can you please add {policy_name} at the end in the command like 'show wireless profile policy detailed {policy_name}' as I mentioned in my comment? Thank you.

**Comment by qduk** [comment]
@choudnik I think your comment might have been on a different PR as I don't see it in this conversation. I updated the file with what I believe you are looking forward. Please let me know! Thanks!

**Review by choudnik — APPROVED** [review]

**Comment by automateyournetwork** [comment]
Hello! I have issues with this parser it is not substituting the variable {policy_name} it is taking it as a literal. When I try to use an f string and varaible or even if I hard code "show wireless profile policy detailed default-policy" the parser tries to use the literal "show wireless profile policy details {policy_name} - it does not replace the policy name

**Pull request merged**
