### PR TITLE
updated show_xconnect.py

### PR DESCRIPTION
**Pull request by tylersiemers**

### CODE REVIEW

**Comment by jeaubin** [comment]
Thanks @tylersiemers - Will look into it

**Comment by zvakhide** [comment]
Hi tylersiemers,

seems you want to change the schema to get "status", 
the easiest way is :
parsed_output = obj.parse()
print(parsed_output['segment_1']['ac   Et0/0(Ethernet)']['segment_2']["mpls 10.55.55.2:1000"]['s2'])
or use a loop to find "s2",

how about  if you have  the output  like below:
Router# show xconnect all

 Legend: XC ST=Xconnect State, S1=Segment1 State, S2=Segment2 State
 UP=Up, DN=Down, AD=Admin Down, IA=Inactive, NH=No Hardware
 XC ST  Segment 1                         S1 Segment 2                         S2
 ------+---------------------------------+--+---------------------------------+--
 UP pri ac   Et0/0(Ethernet)              UP mpls 10.55.55.2:1000              UP
 UP sec ac   Et0/0(Ethernet)             UP mpls 10.55.55.3:1001              DN

according to your changes, the second line would override the first one, this is the output after your changes:
{
    "segment_1": {
        "UP": {
            "segment_2": {
                "UP": {
                    "s2": "DN",
                    "xc": "sec",
                    "st": "mpls 10.55.55.3:1001             "
                }
            },
            "s1": "ac   Et0/0(Ethernet)             "
        }
    }
}

But it has to have all info  so the correct parsed data would be :
{
     "segment_1": {
          "ac   Et0/0(Ethernet)": {
               "segment_2": {
                    "mpls 10.55.55.2:1000": {
                         "s2": "UP",
                         "xc": "UP",
                         "st": "pri"
                    },
                    "mpls 10.55.55.3:1001": {
                         "s2": "DN",
                         "xc": "UP",
                         "st": "sec"
                    }
               },
               "s1": "UP"
          }
     }
}

**Comment by tylersiemers** [comment]
@zvakhide 
Thanks. Yes the second method like this:

{
     "segment_1": {
          "ac   Et0/0(Ethernet)": {
               "segment_2": {
                    "mpls 10.55.55.2:1000": {
                         "s2": "UP",
                         "xc": "UP",
                         "st": "pri"
                    },
                    "mpls 10.55.55.3:1001": {
                         "s2": "DN",
                         "xc": "UP",
                         "st": "sec"
                    }
               },
               "s1": "UP"
          }
     }
}

Is correct how it should show. When testing the parser it wasn't matching on all entries.

**Comment by zvakhide** [comment]
HI tylersiemers,
we put a fix on , please update your genieparser,
pip install genie.libs.parser --upgrade --pre

thanks

**Comment by jeaubin** [comment]
@tylersiemers  - Please let us know if this fixed the issue you were seeing.

**Comment by tylersiemers** [comment]
@jeaubin 
Just tested, it is returning full results now. Thanks for the quick turn around.

Snippet:

{
  "segment_1": {
    "ac Gi0/0/10:5(Eth VLAN)": {
      "s1": "AD",
      "segment_2": {
        "mpls 10.50.15.8:6006": {
          "s2": "DN",
          "st": "sec",
          "xc": "AD"
        },
        "mpls 10.50.15.9:6006": {
          "s2": "DN",
          "st": "pri",
          "xc": "AD"
        }
      }
    },
    "ac Gi0/0/11:5(Eth VLAN)": {
      "s1": "DN",
      "segment_2": {
        "mpls 10.50.15.8:60060": {
          "s2": "DN",
          "st": "sec",
          "xc": "IA"
        },
        "mpls 10.50.15.9:60060": {
          "s2": "DN",
          "st": "pri",
          "xc": "DN"
        }
      }
    }

**Comment by jeaubin** [comment]
Great!  will close this PR

**Pull request closed without merging**
