### PR TITLE
Match IPv6 addresses with A-F characters.

### PR DESCRIPTION
**Pull request by ancker010**
The regexes used were too restrictive. They matched IPv4 addresses, and IPv6 addresses that contain only numbers. (eg, 192.168.0.1, 2001:123::)
They did NOT match any IPv6 addresses with 'a-f' characters. (eg, 2001:456:abc::)

## Description
Updated incorrect/restrictive regex to match all valid IPv4/IPv6 addresses.

## Motivation and Context
The parser was not returning all of the correct results.

## Impact (If any)
I believe there are none.

## Screenshots:
n/a

### CODE REVIEW

**Review by lsheikal — APPROVED** [review]
Thank you for your contribution!!!

**Review by LukasMcClelland — CHANGES_REQUESTED** [review]
Thanks for contributing! 👍 

1 - Please add tests to ensure that your fixes will continue to work when any changes are made to this file in the future.

Tests should be added to these 2 directories:
https://github.com/CiscoTestAutomation/genieparser/tree/master/src/genie/libs/parser/junos/tests/ShowRouteReceiveProtocolExtensive/cli/equal
https://github.com/CiscoTestAutomation/genieparser/tree/master/src/genie/libs/parser/junos/tests/ShowRouteReceiveProtocolPeerAddressExtensive/cli/equal

Some tests already exist there and you can use them as examples but the filenames will need to be different (ie. `golden_output_2_expected.py`, `golden_output_2_output.txt`, and `
golden_output_2_arguments.json`)

More info on folder based tests can be found [here](https://pubhub.devnetcloud.com/media/pyats-development-guide/docs/writeparser/writeparser.html#folder-based-testing-asa-ios-and-iosxe)

2 - Please also add a changelog file. Instructions on how to do this can be found in the [README](https://github.com/CiscoTestAutomation/genieparser#how-to-write-a-changelog-for-your-contribution)

**Comment by ancker010** [comment]
I'll try to get these added in the next few days.

**Comment by ancker010** [comment]
Added tests (they all pass), and added Changelog.

**Review by LukasMcClelland — APPROVED** [review]

**Comment by LukasMcClelland** [comment]
Great job!. Thank you for addressing the comments. Approved and merged

**Pull request merged**
