### PR TITLE
Improve regex for `show ip bgp neighbors`

### PR DESCRIPTION
**Pull request by mzbroch**
## Description
Fix regex in `show ip bgp neighbors` for IOS-XE

## Motivation and Context
Parser was not including Current Prefixes in the following output
```
                                 Sent       Rcvd
  Prefix activity:               ----       ----
    Prefixes Current:             192          3 (Consumes 156 bytes)
```

## Impact (If any)
None

## Checklist:
- I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- I have added tests to cover my changes (If applicable).
- All new and existing tests passed.
- All new code passed compilation.

### CODE REVIEW

**Review by LukasMcClelland — CHANGES_REQUESTED** [review]
Thank you very much for the contribution!

Your code looked fine, so I dug into why tests were failing. 

Turns out the super parser that you improved is inherited by IOS parsers located in: 
```
genieparser/src/genie/libs/parser/ios/show_bgp.py
```
Which means that the `prefixes_current` field will have to be added to the affected parser's `golden_output` files. 

Please update the following expected output files:
```
ios -> ShowBgpAllNeighbors -> golden_output2_expected.py
ios -> ShowBgpAllNeighbors -> golden_output3_expected.py
```
and then run `python ci_folder_parsing.py` from within the `genieparser/tests` directory and ensure the tests don't have errors. 

Good job finding this bug!

**Comment by LukasMcClelland** [comment]
Also, please add a changelog files to document your changes. 

https://github.com/CiscoTestAutomation/genieparser#how-to-write-changelog

**Comment by LukasMcClelland** [comment]
Hi @mzbroch! Just a friendly reminder of this open PR :)

Are you planning on implementing the requested changes?

**Review by jeaubin — APPROVED** [review]

**Review by LukasMcClelland — APPROVED** [review]

**Comment by mzbroch** [comment]
> no update for a while on this PR. so @kazemy from our team will address comments and finish up this PR.

Thanks for putting this together!

**Pull request merged**
