### PR TITLE
IOSXR/NXOS: fix "show static routing" parsers to correctly handle IPv6

### PR DESCRIPTION
**Pull request by vincentbernat**
## Description

The regex to capture IPv6 were incorrect. I tested this on ASR9k,
NCS5k and NX7k. The tests were passing due to IPv6 addresses only
having digits. I have updated them to add non-digits. I have checked
there is no other occurences in the code base, but just to be sure, I
will push a followup commits to update other tests to add a non-digit
in IPv6 addresses.

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [ ] All new code passed compilation.

### CODE REVIEW

**Comment by GerriorL** [comment]
Looks like you'll need to merge the latest code into your branch before it can be tested.

```
git remote add upstream https://github.com/CiscoTestAutomation/genieparser.git
git fetch upstream
git pull upstream
```

**Review by GerriorL — APPROVED** [review]

**Review by domachad — CHANGES_REQUESTED** [review]
Hi Vincent, thank you for your contribution! 
There is just one important thing that needs to be done before we can approve these changes. We are moving away from unittest based testing and using folder-based tests instead.

Can you add folder-based tests that cover your changes over these commands? 
If you pull the latest changes in genieparser, you will notice that some (if not all) of these test files no longer exist.

**Comment by vincentbernat** [comment]
I am not adding new tests. I am only modifying existing tests that failed to detect the problem due to IPv6 only using digits.

**Comment by domachad** [comment]
@vincentbernat 

Unfortunately, I believe I'll have to wait until after the monthly release is over (which will happen this week) to properly review your PR as we're making sweeping changes to parser tests (NXOS tests included). After release you'll be able to see what changes have been made and my comment about the files moving will make more sense.

As for changing existing tests, the common golden rule we follow is to maintain 100% backwards compatibility (when possible) and for parsers this equates to leaving all existing unit tests alone. However, in this case it does seem like overkill to ask for a new 1200 line test file for a change as small as this. I'll check with my team and see what we can do

**Comment by vincentbernat** [comment]
The change itself is super simple: fix the regex to parse IPv6 address. The current regex fails to parse an IPv6 address like 2001:db8::14. This bug is not caught by current tests because all tests are using IPv6 addresses only containing digits. I am modifying a lot of existing tests to ensure such a faulty regex is not present elsewhere.

I have already rebased this PR once because of the previous monthly release moving tests from unittests to folder-based tests, I won't rebase it a second time. The monthly single commit release is a bit rude to contributors like me using the regular pull request workflow.

**Comment by domachad** [comment]
@vincentbernat the conflicts were handled internally and your code was merged. 
I will close this pull request.
Your changes will be available as part of the next release.
Thank you again for your contribution

**Pull request closed without merging**
