### PR TITLE
Improve grammar/wording in README.md

### PR DESCRIPTION
**Pull request by mjbear**
## Description

* Change object-orienting > object-oriented
* Change structured datastructure > structured data
* Change familiarized > familiar
* Remove unnecessary trailing pound/hash # symbol from the guide hyperlink
* Add the word Genie to describe which package
* Split a couple long lines

## Motivation and Context

Improve and polish the readme text

## Impact (If any)

No impact, changes to readme text

## Screenshots:

This is for the readme text

:question: Does the changelog need updated for readme changes?

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [ ] I have added tests to cover my changes (If applicable).
- [ ] All new and existing tests passed.
- [ ] All new code passed compilation.

### CODE REVIEW

**Comment by mjbear** [comment]
@Taarini @lsheikal
Thoughts on this easy win? :wink: :sweat_smile:

**Comment by mjbear** [comment]
> @Taarini @lsheikal Thoughts on this easy win? 😉 😅

\+ @ThomasJRyan since they merged things recently. :wink:

Thoughts?

It's been two weeks ... you all were probably busy so I thought I'd tap you all to revisit this.

**Review by ThomasJRyan — APPROVED** [review]

**Comment by ThomasJRyan** [comment]
Good call on the tap. It's extremely easy to missing PRs here. Thank you @mjbear

**Comment by mjbear** [comment]
> Good call on the tap. It's extremely easy to miss PRs here. Thank you @mjbear

Understood.
Thank you! @ThomasJRyan

**Pull request merged**
