### PR TITLE
convert sros to folder tests

### PR DESCRIPTION
**Pull request by itdependsnetworks**
## Description

convert sros to folder tests

## Motivation and Context

A single testing strategy

## Impact (If any)

N/A

## Screenshots:

N/A

## Checklist:

- [ ] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

### CODE REVIEW

**Review by KamyarZiabari — APPROVED** [review]
Can you send the screen shot of the tests with the new format running and passing please?

**Review by jeaubin — APPROVED** [review]
Can you confirm that all testcases has been migrated?

**Comment by itdependsnetworks** [comment]
Yes

**Comment by xiaoxinz-cisco** [comment]
Hi @itdependsnetworks , do you mind merging it if all tests passed? thanks

**Comment by jeaubin** [comment]
@itdependsnetworks  - ready to merge?

**Comment by tahigash** [comment]
added `sros` since it was missing in `ci_folder_parsing.py`. now we can check `sros` via GitHub actions. and merged latest master to the branch.

**Comment by tahigash** [comment]
@itdependsnetworks just want to confirm again. when we checked with you before, only `iosxr` is the only one which we have not migrated yet. but seems `nxos` is also not yet. you have the migration code in local and not pushed? or both `iosxr` and `nxos` are not migrated yet?

**Comment by LukasMcClelland** [comment]
Hello @itdependsnetworks, thank you choosing to contribute and for putting in the work. 

We're looking to lower our number of open PRs and since this PR has been inactive for a few months, I'll be taking it on myself to resolve the merge conflicts and get this PR merged!

Thanks,
Lukas

**Review by LukasMcClelland — APPROVED** [review]

**Comment by itdependsnetworks** [comment]
Thanks @LukasMcClelland will try and get back to this.

**Pull request merged**
