### PR TITLE
Add 5 new interface names to Common.convert_intf_name

### PR DESCRIPTION
**Pull request by jmdilly**
## Description
This PR adds Dialer, Virtual-Access, Cellular, Virtual-PPP and pseudowire interface types.

## Motivation and Context
Usefull when dealing with PPPoE and LTE CPEs.

## Impact (If any)
None

## Screenshots:
```2021-08-27T13:46:36: %GENIE-INFO: +------------------------------------------------------------------------------+
2021-08-27T13:46:36: %GENIE-INFO: +------------------------------------------------------------------------------+
2021-08-27T13:46:36: %GENIE-INFO: |                                   Summary                                    |
2021-08-27T13:46:36: %GENIE-INFO: +------------------------------------------------------------------------------+
2021-08-27T13:46:36: %GENIE-INFO:  Number of ABORTED                                                            0 
2021-08-27T13:46:36: %GENIE-INFO:  Number of BLOCKED                                                            0 
2021-08-27T13:46:36: %GENIE-INFO:  Number of ERRORED                                                            0 
2021-08-27T13:46:36: %GENIE-INFO:  Number of FAILED                                                             0 
2021-08-27T13:46:36: %GENIE-INFO:  Number of PASSED                                                             2 
2021-08-27T13:46:36: %GENIE-INFO:  Number of PASSX                                                              0 
2021-08-27T13:46:36: %GENIE-INFO:  Number of SKIPPED                                                            0 
2021-08-27T13:46:36: %GENIE-INFO:  Total Number                                                                 2 
2021-08-27T13:46:36: %GENIE-INFO:  Success Rate                                                            100.0% 
2021-08-27T13:46:36: %GENIE-INFO: --------------------------------------------------------------------------------
2021-08-27T13:46:36: %GENIE-INFO:  Total Parsers Missing Unittests                                             52 
2021-08-27T13:46:36: %GENIE-INFO: --------------------------------------------------------------------------------
2021-08-27T13:46:36: %GENIE-INFO:  Total Passing Unittests                                                   1670 
2021-08-27T13:46:36: %GENIE-INFO:  Total Failed Unittests                                                       0 
2021-08-27T13:46:36: %GENIE-INFO:  Total Errored Unittests                                                      1 
2021-08-27T13:46:36: %GENIE-INFO:  Total Unittests                                                           1670 
2021-08-27T13:46:36: %GENIE-INFO: --------------------------------------------------------------------------------
```

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [ ] All new code passed compilation.

### CODE REVIEW

**Review by tahigash — APPROVED** [review]

**Comment by lsheikal** [comment]
@jmdilly kindly resolve the merge conflict. Apart from that the changes looks good. Thank you for your contribution.

**Review by lsheikal — APPROVED** [review]

**Comment by jmdilly** [comment]
Thank you @tahigash and @lsheikal for your review! Merge conflict should be resolved be now.

**Comment by jmdilly** [comment]
Hello @lsheikal, @tahigash, 

Do you still wait anything from me before you can merge this PR ?

Thank you!

**Comment by tahigash** [comment]
@jmdilly sorry for late reply and we are so sorry. we had to deal with repo for some. then we are seen massive conflict on your PR now.
I think hard to fix the conflicts. so, could you please delete your forked repo once. then clone repo again and open PR as new? I pulled about your changes from git history. (hope not missing any).

Sorry for inconvenience and let me know if you need any help on above.

```
commit ad3b6f6984983c6e2032e7ed9a55ce318218581d
Author: Jean-Michel <48059109+jmdilly@users.noreply.github.com>
Date:   Fri Aug 27 13:26:55 2021 +0200

    UTILS : added three interfaces to convert list

    + Vp (Virtual-PPP)
    + Ce (Cellulare)
    + pw (pseudowire)

diff --git a/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst b/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst
index 4f7bd5085..86e1c7cf9 100644
--- a/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst
+++ b/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst
@@ -3,8 +3,8 @@
 --------------------------------------------------------------------------------
 * UTILS
     * Modified Common:
-        * Added Di (Dialer) and Vi (Virtual-Access) to convert list of interfaces
+        * Added Di, Vi, Vp, pw and Ce to convert list of interfaces

 * IOSXE
     * Modified ShowInterfacesDescription
-        * Added a test to check Di and Vi full interface name conversion
\ No newline at end of file
+        * Added two tests to check Di, Vi, Vp, pw and Ce full interface name conversion
\ No newline at end of file
diff --git a/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_expected.py b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_expected.py
new file mode 100644
index 000000000..714895294
--- /dev/null
+++ b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_expected.py
@@ -0,0 +1,39 @@
+expected_output = {
+    'interfaces':
+        {
+            'Cellular0/2/0': { 'description': 'LTE',
+                               'protocol': 'up',
+                               'status': 'up'},
+            'Cellular0/2/1': { 'description': '',
+                        'protocol': 'down',
+                        'status': 'admin down'},
+            'GigabitEthernet0/0/0': { 'description': '',
+                                    'protocol': 'down',
+                                    'status': 'admin down'},
+            'GigabitEthernet0/0/1': { 'description': '',
+                                    'protocol': 'down',
+                                    'status': 'down'},
+            'GigabitEthernet0/1/0': { 'description': '',
+                                    'protocol': 'down',
+                                    'status': 'down'},
+            'GigabitEthernet0/1/1': { 'description': '',
+                                    'protocol': 'up',
+                                    'status': 'up'},
+            'GigabitEthernet0/1/2': { 'description': '',
+                                    'protocol': 'up',
+                                    'status': 'up'},
+            'GigabitEthernet0/1/3': { 'description': '',
+                                    'protocol': 'down',
+                                    'status': 'down'},
+            'pseudowire100001': { 'description': '',
+                        'protocol': 'up',
+                        'status': 'up'},
+            'Vlan1': { 'description': 'LAN1',
+                        'protocol': 'up',
+                        'status': 'up'},
+            'Vlan2': { 'description': 'LAN2',
+                        'protocol': 'up',
+                        'status': 'up'},
+            'Virtual-PPP1': {'description': '', 'protocol': 'up', 'status': 'up'}
+    }
+}
\ No newline at end of file
diff --git a/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_output.txt b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_output.txt
new file mode 100644
index 000000000..c02530af6
--- /dev/null
+++ b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output3_output.txt
@@ -0,0 +1,13 @@
+Interface                      Status         Protocol Description
+Gi0/0/0                        admin down     down
+Gi0/0/1                        down           down
+Gi0/1/0                        down           down
+Gi0/1/1                        up             up
+Gi0/1/2                        up             up
+Gi0/1/3                        down           down
+Ce0/2/0                        up             up       LTE
+Ce0/2/1                        admin down     down
+Vp1                            up             up
+Vl1                            up             up       LAN1
+Vl2                            up             up       LAN2
+pw100001                       up             up
\ No newline at end of file
diff --git a/src/genie/libs/parser/utils/common.py b/src/genie/libs/parser/utils/common.py
index 28116d8f4..945cfc620 100644
--- a/src/genie/libs/parser/utils/common.py
+++ b/src/genie/libs/parser/utils/common.py
@@ -604,7 +604,10 @@ class Common:
                     'BAGG': 'Bridge-Aggregation',  # comware
                     'Ten-GigabitEthernet': 'TenGigabitEthernet',  # HP
                     'Di': 'Dialer',
-                    'Vi': 'Virtual-Access'
+                    'Vi': 'Virtual-Access',
+                    'Ce': 'Cellular',
+                    'Vp': 'Virtual-PPP',
+                    'pw': 'pseudowire'
                 },
             'iosxr':
             # interface formats specific to iosxr

commit a0104459b10f463c443a4ef8e3d7836059e75ec7
Author: Jean-Michel <48059109+jmdilly@users.noreply.github.com>
Date:   Fri Aug 27 13:03:50 2021 +0200

    UTILS : added two interfaces to convert list

    + Di (Dialer)
    + Vi (Virtual-Access)

diff --git a/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst b/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst
new file mode 100644
index 000000000..4f7bd5085
--- /dev/null
+++ b/changelog/undistributed/changelog_ShowInterfacesDescription_20210827124753.rst
@@ -0,0 +1,10 @@
+--------------------------------------------------------------------------------
+                            Fix
+--------------------------------------------------------------------------------
+* UTILS
+    * Modified Common:
+        * Added Di (Dialer) and Vi (Virtual-Access) to convert list of interfaces
+
+* IOSXE
+    * Modified ShowInterfacesDescription
+        * Added a test to check Di and Vi full interface name conversion
\ No newline at end of file
diff --git a/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_expected.py b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_expected.py
new file mode 100644
index 000000000..b54750a6a
--- /dev/null
+++ b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_expected.py
@@ -0,0 +1,73 @@
+expected_output = {
+    'interfaces':
+        {
+            'Dialer1': {'description': 'TEST',
+                        'protocol': 'down',
+                        'status': 'down'},
+            'Dialer2': {'description': 'TEST',
+                        'protocol': 'up',
+                        'status': 'up'},
+            'Dialer3': {'description': '', 'protocol': 'up', 'status': 'up'},
+            'GigabitEthernet0/0/0': {'description': 'WAN',
+                                     'protocol': 'up',
+                                     'status': 'up'},
+            'GigabitEthernet0/0/0.40001': {'description': '',
+                                           'protocol': 'down',
+                                           'status': 'deleted'},
+            'GigabitEthernet0/0/0.4001': {'description': 'WAN PPPOE',
+                                          'protocol': 'up',
+                                          'status': 'up'},
+            'GigabitEthernet0/0/1': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/0': {'description': '',
+                                     'protocol': 'up',
+                                     'status': 'up'},
+            'GigabitEthernet0/1/1': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/2': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/3': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/4': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/5': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/6': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'GigabitEthernet0/1/7': {'description': '',
+                                     'protocol': 'down',
+                                     'status': 'admin down'},
+            'Loopback0': {'description': '',
+                          'protocol': 'up',
+                          'status': 'up'},
+            'Port-channel1': {'description': '',
+                              'protocol': 'down',
+                              'status': 'down'},
+            'Port-channel1.1': {'description': '',
+                                'protocol': 'down',
+                                'status': 'down'},
+            'Port-channel1.2': {'description': '',
+                                'protocol': 'down',
+                                'status': 'down'},
+            'Port-channel1.30004': {'description': '',
+                                    'protocol': 'down',
+                                    'status': 'down'},
+            'Virtual-Access1': {'description': '', 'protocol': 'up', 'status': 'up'},
+            'Virtual-Access2': {'description': 'TEST',
+                                'protocol': 'up',
+                                'status': 'up'},
+            'Virtual-Access3': {'description': '',
+                                'protocol': 'down',
+                                'status': 'down'},
+            'Vlan1': {'description': 'LAN',
+                      'protocol': 'up',
+                      'status': 'up'}
+        }
+}
diff --git a/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_output.txt b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_output.txt
new file mode 100644
index 000000000..0eabb4984
--- /dev/null
+++ b/src/genie/libs/parser/iosxe/tests/ShowInterfacesDescription/cli/equal/golden_interface_output2_output.txt
@@ -0,0 +1,25 @@
+Interface                      Status         Protocol Description
+Gi0/0/0                        up             up       WAN
+Gi0/0/0.4001                   up             up       WAN PPPOE
+Gi0/0/0.40001                  deleted        down
+Gi0/0/1                        admin down     down
+Gi0/1/0                        up             up
+Gi0/1/1                        admin down     down
+Gi0/1/2                        admin down     down
+Gi0/1/3                        admin down     down
+Gi0/1/4                        admin down     down
+Gi0/1/5                        admin down     down
+Gi0/1/6                        admin down     down
+Gi0/1/7                        admin down     down
+Di1                            down           down     TEST
+Di2                            up             up       TEST
+Di3                            up             up
+Lo0                            up             up
+Po1                            down           down
+Po1.1                          down           down
+Po1.2                          down           down
+Po1.30004                      down           down
+Vi1                            up             up
+Vi2                            up             up       TEST
+Vi3                            down           down
+Vl1                            up             up       LAN
\ No newline at end of file
diff --git a/src/genie/libs/parser/utils/common.py b/src/genie/libs/parser/utils/common.py
index 45fe88029..28116d8f4 100644
--- a/src/genie/libs/parser/utils/common.py
+++ b/src/genie/libs/parser/utils/common.py
@@ -602,7 +602,9 @@ class Common:
                     'tu': 'Tunnel',
                     'M-E': 'M-Ethernet',  # comware
                     'BAGG': 'Bridge-Aggregation',  # comware
-                    'Ten-GigabitEthernet': 'TenGigabitEthernet'  # HP
+                    'Ten-GigabitEthernet': 'TenGigabitEthernet',  # HP
+                    'Di': 'Dialer',
+                    'Vi': 'Virtual-Access'
                 },
             'iosxr':
             # interface formats specific to iosxr

**Review by tahigash — CHANGES_REQUESTED** [review]
We are so sorry. as mentioned, please re-fork repo then open new PR with your change.

**Pull request closed without merging**
