### PR TITLE
Added hsrp event history parsers

### PR DESCRIPTION
**Pull request by divya883**
## Description
Added parsers for the commands 'show hsrp internal event-history errors', 'show hsrp internal event-history msgs' and 'show hsrp internal event-history debugs' for nxos.
( changes from PR #476 )

## Motivation and Context
I was working with hsrp as part of a project and wanted to retrieve related info and found that there were no parsers for the above commands.

## Impact (If any)
No negative impact expected.

## Screenshots:
show hsrp internal event-history errors

2021-10-13T20:14:11: %GENIE-INFO: |   |-- ShowHsrpEventHistoryErrors                                        PASSED
2021-10-13T20:14:11: %GENIE-INFO: |   |   |-- Step 1: nxos -> ShowHsrpEventHistoryErrors                    PASSED
2021-10-13T20:14:11: %GENIE-INFO: |   |   |-- Step 1.1: Test Golden -> nxos -> ShowHsrpEventHistoryEr...    PASSED
2021-10-13T20:14:11: %GENIE-INFO: |   |   |-- Step 1.1.1: Gold -> nxos -> ShowHsrpEventHistoryErrors ...    PASSED
2021-10-13T20:14:11: %GENIE-INFO: |   |   |-- Step 1.2: Test Empty -> nxos -> ShowHsrpEventHistoryErrors    PASSED
2021-10-13T20:14:11: %GENIE-INFO: |   |   `-- Step 1.2.1: Empty -> nxos -> ShowHsrpEventHistoryErrors...    PASSED

show hsrp internal event history msgs

2021-10-13T20:16:21: %GENIE-INFO: |-- nxos                                                                  PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |-- setup                                                             PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |-- ShowHsrpEventHistoryMsgs                                          PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |   |-- Step 1: nxos -> ShowHsrpEventHistoryMsgs                      PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |   |-- Step 1.1: Test Golden -> nxos -> ShowHsrpEventHistoryMsgs     PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |   |-- Step 1.1.1: Gold -> nxos -> ShowHsrpEventHistoryMsgs ->...    PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |   |-- Step 1.2: Test Empty -> nxos -> ShowHsrpEventHistoryMsgs      PASSED
2021-10-13T20:16:21: %GENIE-INFO: |   |   `-- Step 1.2.1: Empty -> nxos -> ShowHsrpEventHistoryMsgs -...    PASSED

show hsrp event history debugs

2021-10-13T20:17:12: %GENIE-INFO: |-- nxos                                                                  PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |-- setup                                                             PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |-- ShowHsrpEventHistoryDebugs                                        PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |   |-- Step 1: nxos -> ShowHsrpEventHistoryDebugs                    PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |   |-- Step 1.1: Test Golden -> nxos -> ShowHsrpEventHistoryDe...    PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |   |-- Step 1.1.1: Gold -> nxos -> ShowHsrpEventHistoryDebugs ...    PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |   |-- Step 1.2: Test Empty -> nxos -> ShowHsrpEventHistoryDebugs    PASSED
2021-10-13T20:17:12: %GENIE-INFO: |   |   `-- Step 1.2.1: Empty -> nxos -> ShowHsrpEventHistoryDebugs...    PASSED

## Checklist:

- [x] I have updated the changelog.
- [ ] I have updated the documentation (If applicable).
- [x] I have added tests to cover my changes (If applicable).
- [x] All new and existing tests passed.
- [x] All new code passed compilation.

### CODE REVIEW

**Comment by danielgraziano** [comment]
Unfortunately you will need to save your changes into a text file, and start over from the latest master. There were some changes needed in the master branch which is causing these conflicts.

**Review by LukasMcClelland — COMMENTED** [review]
@divya883 Would it be possible for you to implement Daniel's suggestion sometime this week?

**Comment by divya883** [comment]
> @divya883 Would it be possible for you to implement Daniel's suggestion sometime this week?

Hi Lukas, yes I'll do it by this week

**Comment by divya883** [comment]
Hi @LukasMcClelland @danielgraziano , I tried copying all my changes to a new file, deleting them from my workspace, pulling the master and adding my changes again. But that doesn't seem to solve the problem. How do I resolve this? Should I create a new pull request again?

**Comment by danielgraziano** [comment]
@divya883 

First you'll have to save your parsers that you wrote and want to contribute. 

Second, you'll need to delete your copy of the master (divya883:mater) and then re-pull the master branch from the remote (CiscoTestAutomation:master). This step is required because the history had to be re-written :(.

Third, copy your saved parsers/tests back into your copy of master (divya883:master) and then create a pull request

**Comment by danielgraziano** [comment]
Alternatively just save your changes, delete the fork, re-fork, copy your changes back in

**Review by danielgraziano — CHANGES_REQUESTED** [review]
I'm just requesting changes so that this PR doesnt show up in my filters

**Comment by divya883** [comment]
opened a new PR #594

**Pull request closed without merging**
